import pandas as pd
import matplotlib.pyplot as plt

baseline = pd.read_csv("data/raw/spike1.txt", sep="\t")
mem_spike = pd.read_csv("data/raw/mem_spike.txt", sep="\t")
mem_leak = pd.read_csv("data/raw/mem_leak.txt", sep="\t")
cpu_spike = pd.read_csv("data/raw/cpu_spike.txt", sep="\t")
plt.figure()
plt.plot(baseline["wtime"], baseline["rss"], label="Baseline")
plt.plot(mem_spike["wtime"], mem_spike["rss"], label="Memory Spike")
plt.plot(mem_leak["wtime"], mem_leak["rss"], label="Memory Leak")
plt.legend()
plt.xlabel("Time (s)")
plt.ylabel("RSS (KB)")
plt.title("Memory Behaviour Comparison")
plt.savefig("plots/memory_comparison.png", dpi=300)
plt.show()

plt.figure()
plt.plot(cpu_spike["wtime"], cpu_spike["utime"])
plt.xlabel("Time (s)")
plt.ylabel("User CPU Time")
plt.title("CPU Runaway Behaviour")
plt.savefig("plots/cpu_runaway.png", dpi=300)
plt.show()

plt.figure()
plt.plot(baseline["wtime"], baseline["rss"])
plt.xlabel("Time (seconds)")
plt.ylabel("RSS (KB)")
plt.title("Baseline Memory Usage")
plt.savefig("plots/baseline_memory.png", dpi=300)
plt.show()

plt.figure()
plt.plot(mem_spike["wtime"], mem_spike["rss"])
plt.xlabel("Time (seconds)")
plt.ylabel("RSS (KB)")
plt.title("Memory Spike Behaviour")
plt.savefig("plots/memory_spike.png", dpi=300)
plt.show()

plt.figure()
plt.plot(mem_leak["wtime"], mem_leak["rss"])
plt.xlabel("Time (seconds)")
plt.ylabel("RSS (KB)")
plt.title("Memory Leak Behaviour")
plt.savefig("plots/memory_leak.png", dpi=300)
plt.show()